/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSetupRouteImport } from './routes/_public/setup'
import { Route as PublicPairRouteImport } from './routes/_public/pair'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPersonasRouteImport } from './routes/_app/personas'
import { Route as AppMemoriesRouteImport } from './routes/_app/memories'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSetupRoute = PublicSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPairRoute = PublicPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => PublicRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonasRoute = AppPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/memories': typeof AppMemoriesRoute
  '/personas': typeof AppPersonasRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/pair': typeof PublicPairRoute
  '/setup': typeof PublicSetupRoute
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/memories': typeof AppMemoriesRoute
  '/personas': typeof AppPersonasRoute
  '/settings': typeof AppSettingsRoute
  '/skills': typeof AppSkillsRoute
  '/pair': typeof PublicPairRoute
  '/setup': typeof PublicSetupRoute
  '/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/memories': typeof AppMemoriesRoute
  '/_app/personas': typeof AppPersonasRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_public/pair': typeof PublicPairRoute
  '/_public/setup': typeof PublicSetupRoute
  '/_public/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/dashboard'
    | '/memories'
    | '/personas'
    | '/settings'
    | '/skills'
    | '/pair'
    | '/setup'
    | '/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/dashboard'
    | '/memories'
    | '/personas'
    | '/settings'
    | '/skills'
    | '/pair'
    | '/setup'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/memories'
    | '/_app/personas'
    | '/_app/settings'
    | '/_app/skills'
    | '/_public/pair'
    | '/_public/setup'
    | '/_public/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/setup': {
      id: '/_public/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof PublicSetupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pair': {
      id: '/_public/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PublicPairRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personas': {
      id: '/_app/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AppPersonasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memories': {
      id: '/_app/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMemoriesRoute: typeof AppMemoriesRoute
  AppPersonasRoute: typeof AppPersonasRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMemoriesRoute: AppMemoriesRoute,
  AppPersonasRoute: AppPersonasRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicPairRoute: typeof PublicPairRoute
  PublicSetupRoute: typeof PublicSetupRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPairRoute: PublicPairRoute,
  PublicSetupRoute: PublicSetupRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
