/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as PublicSetupRouteImport } from './routes/_public/setup'
import { Route as PublicPairRouteImport } from './routes/_public/pair'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthSkillsRouteImport } from './routes/_auth/skills'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthPersonasRouteImport } from './routes/_auth/personas'
import { Route as AuthChatRouteImport } from './routes/_auth/chat'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const PublicSetupRoute = PublicSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPairRoute = PublicPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthSkillsRoute = AuthSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonasRoute = AuthPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatRoute = AuthChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof AuthChatRoute
  '/personas': typeof AuthPersonasRoute
  '/settings': typeof AuthSettingsRoute
  '/skills': typeof AuthSkillsRoute
  '/login': typeof PublicLoginRoute
  '/pair': typeof PublicPairRoute
  '/setup': typeof PublicSetupRoute
  '/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/chat': typeof AuthChatRoute
  '/personas': typeof AuthPersonasRoute
  '/settings': typeof AuthSettingsRoute
  '/skills': typeof AuthSkillsRoute
  '/login': typeof PublicLoginRoute
  '/pair': typeof PublicPairRoute
  '/setup': typeof PublicSetupRoute
  '/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/chat': typeof AuthChatRoute
  '/_auth/personas': typeof AuthPersonasRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/skills': typeof AuthSkillsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/pair': typeof PublicPairRoute
  '/_public/setup': typeof PublicSetupRoute
  '/_auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/personas'
    | '/settings'
    | '/skills'
    | '/login'
    | '/pair'
    | '/setup'
    | '/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/personas'
    | '/settings'
    | '/skills'
    | '/login'
    | '/pair'
    | '/setup'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/chat'
    | '/_auth/personas'
    | '/_auth/settings'
    | '/_auth/skills'
    | '/_public/login'
    | '/_public/pair'
    | '/_public/setup'
    | '/_auth/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/setup': {
      id: '/_public/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof PublicSetupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pair': {
      id: '/_public/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PublicPairRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/skills': {
      id: '/_auth/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthSkillsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/personas': {
      id: '/_auth/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthPersonasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthChatRoute: typeof AuthChatRoute
  AuthPersonasRoute: typeof AuthPersonasRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSkillsRoute: typeof AuthSkillsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChatRoute: AuthChatRoute,
  AuthPersonasRoute: AuthPersonasRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSkillsRoute: AuthSkillsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicPairRoute: typeof PublicPairRoute
  PublicSetupRoute: typeof PublicSetupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicPairRoute: PublicPairRoute,
  PublicSetupRoute: PublicSetupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
